In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\SUBHAM DEY\Empty Folder\substitution.csv")

In [6]:
df.head()

Day  Period Class    Subject Absent_Faculty Substitute_Faculty  \
0  Monday       1    9A       Math        Mr. Das                NaN   
1  Monday       1    9B    English        Ms. Sen            Mr. Roy   
2  Monday       1    9C    Bengali   Ms. Banerjee                NaN   
3  Monday       1   10A    Physics      Mr. Ghosh     Ms. Chatterjee   
4  Monday       1   10B  Chemistry      Ms. Dutta                NaN   

   Was_Free_That_Period  Substitution_Success  
0                     0                     0  
1                     1                     1  
2                     0                     0  
3                     1                     1  
4                     0                     0

In [7]:
df.fillna('NoSubstitute',inplace=True)

In [8]:
label_encoders = {}

In [14]:
categorical_cols = ['Day', 'Class', 'Subject', 'Absent_Faculty', 'Substitute_Faculty']

In [15]:
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [28]:
df.head()

Day  Period  Class  Subject  Absent_Faculty  Substitute_Faculty  \
0    1       1      9       10               3                  12   
1    1       1     10        7              13                   6   
2    1       1     11        1               8                  12   
3    1       1      0       11               4                   8   
4    1       1      1        4               9                  12   

   Was_Free_That_Period  Substitution_Success  
0                     0                     0  
1                     1                     1  
2                     0                     0  
3                     1                     1  
4                     0                     0

In [16]:
X = df.drop(columns='Substitution_Success')
y = df['Substitution_Success']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [31]:
y_pred = rf_model.predict(X_test)

In [20]:
report = classification_report(y_test,y_pred, output_dict=True)

In [21]:
report

{'0': {'precision': 1.0,
  'recall': 0.9629629629629629,
  'f1-score': 0.9811320754716981,
  'support': 54.0},
 '1': {'precision': 0.9545454545454546,
  'recall': 1.0,
  'f1-score': 0.9767441860465116,
  'support': 42.0},
 'accuracy': 0.9791666666666666,
 'macro avg': {'precision': 0.9772727272727273,
  'recall': 0.9814814814814814,
  'f1-score': 0.9789381307591049,
  'support': 96.0},
 'weighted avg': {'precision': 0.9801136363636364,
  'recall': 0.9791666666666666,
  'f1-score': 0.9792123738481789,
  'support': 96.0}}

In [22]:
conf_matrix = confusion_matrix(y_test, y_pred)

In [23]:
conf_matrix

array([[52,  2],
       [ 0, 42]], dtype=int64)

In [24]:
feature_importances = rf_model.feature_importances_

In [25]:
feature_importances

array([0.0366807 , 0.00356891, 0.04239678, 0.00371167, 0.00820705,
       0.43443284, 0.47100204])

In [27]:
# Sample test data in dictionary form (human-readable)
sample_data = {
    'Day': ['Monday'],
    'Period': [3],
    'Class': ['10A'],
    'Subject': ['English'],
    'Absent_Faculty': ['Ms. Banerjee'],
    'Substitute_Faculty': ['Mr. Roy'],
    'Was_Free_That_Period': [1]
}

# Convert to DataFrame
sample_df = pd.DataFrame(sample_data)

for col in categorical_cols:
    sample_df[col] = sample_df[col].apply(lambda x: x if x in label_encoders[col].classes_ else 'Unknown')

    # If 'Unknown' wasn't in training, add it manually to the classes_
    if 'Unknown' not in label_encoders[col].classes_:
        label_encoders[col].classes_ = np.append(label_encoders[col].classes_, 'Unknown')

    sample_df[col] = label_encoders[col].transform(sample_df[col])


# Predict substitution success
sample_prediction = rf_model.predict(sample_df)
sample_prediction_proba = rf_model.predict_proba(sample_df)

sample_df, sample_prediction[0], sample_prediction_proba[0]


(   Day  Period  Class  Subject  Absent_Faculty  Substitute_Faculty  \
 0    1       3     12       14              15                  13   
 
    Was_Free_That_Period  
 0                     1  ,
 0,
 array([0.69, 0.31]))

In [35]:
rf_model1 = RandomForestClassifier(n_estimators=10, random_state=42)
rf_model1.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=42)

In [36]:
y_pred1 = rf_model1.predict(X_test)

In [37]:
report1 = classification_report(y_test,y_pred, output_dict=True)

In [38]:
report1

{'0': {'precision': 1.0,
  'recall': 0.9629629629629629,
  'f1-score': 0.9811320754716981,
  'support': 54.0},
 '1': {'precision': 0.9545454545454546,
  'recall': 1.0,
  'f1-score': 0.9767441860465116,
  'support': 42.0},
 'accuracy': 0.9791666666666666,
 'macro avg': {'precision': 0.9772727272727273,
  'recall': 0.9814814814814814,
  'f1-score': 0.9789381307591049,
  'support': 96.0},
 'weighted avg': {'precision': 0.9801136363636364,
  'recall': 0.9791666666666666,
  'f1-score': 0.9792123738481789,
  'support': 96.0}}